### ISSUE TITLE
Remove location text messages

### ISSUE THREAD

**Issue by trollollol123** [brutalcs/BrutalCS#5]
Would be nice to remove the annoying chat spam of a players map location when camping detected. But keep the camp warning message for the specific camper.

Also there is lots of useless crap in the plugin such as punishments like blind, slap, slay and money.  Also weapon configs and stuff about bomb plant, bomb drop etc and map type de_, cs_ etc. All this could be removed if its any point to spend time on that?

https://github.com/IT-KiLLER/Sourcemod-plugins/tree/master/Plugins/anticamp

**Comment by B3none** [comment]
Completed.
