### ISSUE TITLE
Anti Camper bugs gameME logging

### ISSUE THREAD

**Issue by trollollol123** [brutalcs/BrutalCS#7]
> The problem is a log line which is triggering a "camper" action:
> 
> E011: (IGNORED) "WOPSl" <P:5784673,U:1281,W:76561198213717757,T:TERRORIST> triggered "camper"
> 
> A correct log line would be:
> 
> "WOPSl" <P:1682660,U:1281,W:1:126726014,T:TERRORIST> triggered "headshot"
> You need to fix the logging of the unique id to match Steam ID. Might it be possible you are logging the community id?
> 
> Plesae check this issue and this is the problem, Your camper action will create new player profiles starting with 1,000 points.

**Comment by B3none** [comment]
I removed the logging line for campers which should've fixed the bug you've been experiencing with gameME
